name: CMake Build (x86 Release Only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Developer Command Prompt for Microsoft Visual C++
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Set up Ninja
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.11.1

    - name: CMake Configure
      run: cmake --preset x86-release

    - name: CMake Build
      run: cmake --build .build/x86-release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ExHIBIT_KeyFinder-x86-release
        # 根據您的 Main CMakeLists 設定，32 位元會輸出至 .bin/x32/release/
        path: |
          .bin/x32/release/*.exe
          .bin/x32/release/*.dll
        if-no-files-found: error
